// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DIFEST 2025 | Digital Festival & Innovation",
  description:
    "Discover DIFEST 2025, the international digital festival showcasing innovation and technology.",
  keywords:
    "DIFEST 2025, Digital Festival, Innovation, Technology, Competition",
  robots: "index, follow",
  openGraph: {
    title: "DIFEST 2025 | Digital Festival & Innovation",
    description:
      "Discover DIFEST 2025, the international digital festival showcasing innovation and technology.",
    url: "https://www.difest2025.com",
    siteName: "DIFEST 2025",
    images: [
      {
        url: "https://www.difest2025.com/banner.jpg",
        width: 1200,
        height: 630,
        alt: "DIFEST 2025 Banner",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "DIFEST 2025 | Digital Festival & Innovation",
    description:
      "Discover DIFEST 2025, the international digital festival showcasing innovation and technology.",
    images: ["https://www.difest2025.com/banner.jpg"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
